[env:nologo_esp32c3_super_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = nologo_esp32c3_super_mini
framework = arduino
upload_port = COM23
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    adafruit/Adafruit AS7341
    adafruit/Adafruit BusIO
    sensirion/Sensirion I2C SCD4x

lib_extra_dirs = ../shared

